### PR TITLE
initial fastlane structures

### PR DESCRIPTION
**Pull request by IzzySoft**
As discussed in #861 – and based on your Google Play listing (with some adjustments). Be welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/snippets/1895688) to build upon this :smiley:

### CODE REVIEW

**Comment by marcelklehr** [comment]
> based on your Google Play listing

Whaat, my Google Play listing finally got through review and was published??? Yaay :tada:

**Comment by IzzySoft** [comment]
Looks like. My lazy approach to initialize Fastlane: `./createmeta <packageName>`. Uses [GooglePlayWebServiceAPI](https://github.com/BaseMax/GooglePlayWebServiceAPI) (which I contributed to) to retrieve summary, description, screenshots, icon, featureGraphic from Play and convert them to Fastlane. Then I just need to go over that and fine-tune.

But as you can see, it goes much faster with my repo. Once decided, it's done with the same day :smiley: Thanks for merging!

**Comment by marcelklehr** [comment]
Thanks for the PR :hearts:

**Comment by IzzySoft** [comment]
Gladly! Thanks for the app :smiley:

While I'm using NC Bookmarks as a kind of "read it later list" with my main instance, maybe I should give floccus a try with my other instance to see how well it syncs bookmarks. Has been a while since I last did such a thing, and at that time floccus didn't support "folder structures" (or had issues with that, I don't remember correctly). Guess when I sync a huge collection from one browser, it should be returned to another browser whith the structure kept intact meanwhile?

**Comment by IzzySoft** [comment]
Thanks for confirming! And yes, "last time" certainly was more than a year ago :smile:

**Pull request merged**
